name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    container: mariadb:latest

    services:
      mysql-test-qs:
        image: mysql:latest
        env:
          MYSQL_DATABASE: qs_test
          MYSQL_USER: homestead_test
          MYSQL_PASSWORD: secret_test
          MYSQL_ROOT_PASSWORD: root
          
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction

      - name: Set up environment variables
        run: cp .env.testing .env

      - name: Generate application key
        run: php artisan key:generate --ansi
        
      - name: Run database migrations
        run: php artisan migrate --env=testing --force

      - name: Run tests
        run: vendor/bin/phpunit
