name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mariadb:latest
        command: --lower_case_table_names=1
        container_name: mysql-test-qs
        platform: linux/x86_64
        restart: unless-stopped
        tty: true
        ports:
          - "3307:3306"
        volumes:
          - ./mysql_test:/var/lib/mysql
        environment:
          MYSQL_DATABASE: qs_test
          MYSQL_USER: homestead_test
          MYSQL_PASSWORD: secret_test
          MYSQL_ROOT_PASSWORD: secret_test
        networks:
          - laravel

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction

      - name: Set up environment variables
        run: cp .env.testing .env

      - name: Generate application key
        run: php artisan key:generate --ansi

      - name: Run database migrations
        run: php artisan migrate --env=testing --force

      - name: Run tests
        run: vendor/bin/phpunit
